cidade: João Pessoa
total: 64
bairros:
- Aeroclube
- Altiplano
- Alto do Céu
- Alto do Mateus
- Anatólia
- Bancários
- Barra de Gramame
- Bessa
- Brisamar
- Cabo Branco
- Castelo Branco
- Centro
- Cidade dos Colibris
- Costa do Sol
- Costa e Silva
- Cristo Redentor
- Cruz das Armas
- Cuiá
- Distrito Industrial
- Ernesto Geisel
- Ernâni Sátiro
- Estados
- Expedicionários
- Funcionários
- Gramame
- Grotão
- Ilha do Bispo
- Indústrias
- Ipês
- Jaguaribe
- Jardim Cidade Universitária
- Jardim Oceania
- Jardim São Paulo
- Jardim Veneza
- José Américo
- João Agripino
- João Paulo II
- Manaíra
- Mandacaru
- Mangabeira
- Miramar
- Mumbaba
- Mussuré
- Muçumagro
- Oitizeiro
- Padre Zé
- Paratibe
- Pedro Gondim
- Penha
- Planalto da Boa Esperança
- Ponta do Seixas
- Portal do Sol
- Róger
- São José
- Tambauzinho
- Tambaú
- Tambiá
- Torre
- Treze de Maio
- Trincheiras
- Valentina de Figueiredo
- Varadouro
- Varjão
- Água Fria
